# Site settings
title: CI and CD with GitHub
description: DevOpsDays Amsterdam
email: jouni.leino@siili.com
twitter_username: sapfanboy
github_username:  jounile
baseurl:
url: https://jounile-ci-cd-workshop.herokuapp.com/
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
